pages:
  script:
    - mkdir .public
    - cp index.html .public/
    - cp -r * .public/  # Include other assets like images, styles, scripts
  artifacts:
    paths:
      - .public
  only:
    - main
